import os


IS_LOCAL = True

if 'GOOGLE_CLOUD_PROJECT' in os.environ and 'GOOGLE_CLOUD_PROJECT' in os.environ:
    IS_LOCAL = False

GCP_PROJECT_ID = "LOCAL"
GAE_SERVICE = "SERVICE"
GAE_VERSION = "1"
GAE_INSTANCE = "1"
GAE_DEPLOYMENT_ID = "1"

if not IS_LOCAL:
    GCP_PROJECT_ID = os.getenv('GOOGLE_CLOUD_PROJECT', GCP_PROJECT_ID)
    GAE_SERVICE = os.getenv('GAE_SERVICE', GAE_SERVICE)
    GAE_VERSION = os.getenv('GAE_VERSION', GAE_VERSION)
    GAE_INSTANCE = os.getenv('GAE_INSTANCE', GAE_INSTANCE)
    GAE_DEPLOYMENT_ID = os.getenv('GAE_DEPLOYMENT_ID', GAE_DEPLOYMENT_ID)

GCP_LOCATION = "us-central1"

PUB_SUB_ENALBED = False

if not IS_LOCAL:
    PUB_SUB_ENALBED = True

MESSAGE_ENTITY_PUBSUB_TOPIC_NAME = "testop1"
MESSAGE_PUBSUB_TOPIC_NAME = "topstdem1"

MESSAGE_KIND = "Message"

SECRETY_KEY = b'mysecret'

CLOUD_STORAGE_BUCKET = "tempgcpbucket1"

GITHUB_REPO = "realkinetic"

TASK_QUEUE_NAME = "queue1"

BQ_DATASET_ID = "gcpdemo"
